= Guía de inicio rápido

El propósito de esta guía es explicar brevemente cómo integrar una base de datos https://clickhouse.com/[ClickHouse] en la plataforma _Stratio Generative AI Data Fabric_.

== Prerrequisitos

Puedes encontrar los prerrequisitos para la instalación del conector de SSCC ClickHouse en la xref:clickhouse:operations-guide.adoc#_prerrequisitos[Guía de operaciones].

NOTE: Ten en cuenta que en esta guía de inicio rápido se utilizará el *modo de autenticación con usuario y contraseña*.

== Descubre tus datos

=== Agente de descubrimiento

Para instalar un agente de descubrimiento de _Stratio Data Governance_ para ClickHouse debes seleccionar en *'_Stratio Command Center_' -> 'Deploy a Service' -> 'Connectors Data Warehouse'* el agente "ClickHouse Agent".

En la instalación debes añadir la información correspondiente a la instancia de la base de datos a descubrir, además de las URL del repositorio de conectores donde se almacenan los artefactos necesarios y subir las credenciales de acceso a _Stratio KMS_.

Los campos más importantes a rellenar son:

* *_Root discovery path_*: ruta desde la cual quieres descubrir los metadatos de forma recursiva. Ejemplo: _/schema_to_be_discovered,/schema_to_be_discovered2_.
* *_Custom Service URL_*: URL JDBC usada para conectarse a ClickHouse. Ejemplo: _jdbc:clickhouse://clickhouseserver.labs.stratio.com:8123/_.
* *_Access credentials_*: nombre del secreto creado en _Stratio KMS_. Ejemplo:_clickhouse-secret_.
* *_SSCC driver location_*: URL donde se encuentra el artefacto en el repositorio de conectores que contendrá el JAR del conector ClickHouse. Ejemplo: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-clickhouse-0.3_2.12-1.0.x.jar`.

TIP: Puedes consultar más información sobre el resto de parámetros de configuración en la xref:clickhouse:operations-guide.adoc[guía de operaciones].

Una vez terminado el proceso de descubrimiento, el almacén de datos aparecerá en la interfaz de usuario de _Stratio Data Governance_.

== Virtualiza tus datos

=== Agente de Eureka

Para el uso de la BDL es necesario configurar el agente de Eureka con el conector de ClickHouse. Para ello, hay que añadir las URL de los artefactos necesarios en la variable `Additional jars`:

* _Additional jars_: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-clickhouse-0.3_2.12-1.0.x.jar`.

=== _Stratio Virtualizer_

Para el uso de _Stratio Virtualizer_ es necesario tener configurado el conector de ClickHouse. Para ello, debes añadir las URL de los artefactos necesarios en la variable `JDBC Drivers URL List` y xref:clickhouse:operations-guide.adoc[subir las credenciales de acceso a _Stratio KMS_].

* _JDBC Drivers URL List_: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-clickhouse-0.3_2.12-1.0.x.jar`.

== Transforma tus datos

=== _Stratio Rocket_

Para el uso de _Stratio Rocket_ es necesario tener configurado el conector de ClickHouse. Para ello, debes añadir las URL de los artefactos necesarios en la variable 'Customized deployment' -> 'Settings' -> 'Classpath' -> `Rocket extra jars` y xref:clickhouse:operations-guide.adoc[subir las credenciales de acceso a _Stratio KMS_] para _Stratio Rocket_ y sus _workflows_.

En el ejemplo que se está siguiendo, _Stratio Rocket_ quedaría de esta manera:

* _Rocket extra jars_: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-clickhouse-0.3_2.12-1.0.x.jar`.

Tras aplicar estos cambios, deberías poder acceder a la colección virtualizada de ClickHouse mediante consultas SQL directamente en el catálogo o mediante un "input" de _Stratio Virtualizer_ en un _workflow_.

=== _Stratio Intelligence_

Previo a la integración con el conector es necesario configurar _Stratio Intelligence_, tal y como aparece descrito en xref:ROOT:quick-start-guide#_stratio_intelligence[la guía de inicio rápido general].

Una vez esté configurado _Stratio Intelligence_, tienes que añadir el conector y el _driver JDBC_ de ClickHouse al directorio _artifacts/spark++_++jars_ y xref:clickhouse:operations-guide.adoc[subir las credenciales de acceso a _Stratio KMS_].

Para la subida de los artefactos, estos se deben descargar en el directorio _artifacts/spark++_++jars_ dentro del _workspace_ de _Stratio Intelligence_ realizando una petición cURL.

En el caso que se está tratando, se podría realizar la siguiente petición:

[source,bash]
----
curl http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-clickhouse-0.3_2.12-1.0.x.jar --output sscc-clickhouse-0.3_2.12-1.0.x.jar
----

Una vez configurado esto, podrás acceder a las tablas que se han virtualizado de la base de datos ClickHouse externa.
