= Guía de inicio rápido

El propósito de esta guía es explicar brevemente cómo integrar el modelo de datos de la plataforma SAS® Viya® en la plataforma _Stratio Generative AI Data Fabric_.

== Prerrequisitos

Puedes encontrar los prerrequisitos para la instalación del conector de SSCC SAS® Viya® en la xref:sas-viya:operations-guide.adoc#_prerrequisitos[guía de operaciones].

NOTE: Ten en cuenta que en esta guía de inicio rápido se utilizará el *modo de autenticación MD5*.

== Descubre tus datos

=== Agente de descubrimiento

Para instalar un agente de descubrimiento de _Stratio Data Governance_ para SAS® Viya® debes seguir la ruta '_Stratio Command Center_' -> 'Deploy a Service' -> 'Connectors Data Warehouse' y seleccionar el agente "SAS Agent".

En la instalación debes añadir la información correspondiente al tipo de recurso que quieras descubrir, como se describe a continuación:

. SAS Cloud Analytic Server (CAS). Debes seleccionar el nombre del servidor CAS de la instancia SAS® Viya®. Ejemplo: `sas-shared-default`.
. SAS Programming Runtime Environment Server (SPRE). Debes seleccionar el ID del contexto de cómputo del servidor SPRE de SAS® Viya®. Ejemplo: `48013087-c73b-49d6-9f15-87da2183a3aa`.

Además, debes añadir las URL del repositorio de conectores donde se almacenan los artefactos necesarios y subir las credenciales de acceso a _Stratio KMS_.

Los campos más importantes a rellenar en la instalación son:

* *_Root discovery path_*: ruta desde la cual quieres descubrir los metadatos de forma recursiva.
* *_Custom Service URL_*: URL JDBC usada para conectarse a SAS® Viya®. Ejemplo: `https://connectors.westeurope.cloudapp.azure.com`.
* *_Access credentials_*: nombre del secreto creado en _Stratio KMS_. Ejemplo: `sas-secret`.
* *_SAS provider type_*: tipo de recurso a descubrir. Puede ser `CAS` o `Compute`.
* *_SSCC driver location_*: URL donde se encuentra el artefacto en el repositorio de conectores que contendrá el JAR del conector SSCC SAS® Viya®. Ejemplo: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x.jar`.
* *_Should discover unloaded resources in CAS memory_*: "True" si se deben descubrir tablas que no están cargadas en memoria CAS y "False" si sólo se deben descubrir tablas que ya estén cargadas en memoria CAS.

TIP: Puedes consultar más información sobre el resto de parámetros de configuración en la xref:sas-viya:operations-guide.adoc[guía de operaciones].

Una vez terminado el proceso de descubrimiento, el almacén de datos aparecerá en la interfaz de usuario de _Stratio Data Governance_.

== Virtualiza tus datos

=== Agente de Eureka

Para el uso de la BDL es necesario configurar el agente de Eureka con el conector SSCC SAS® Viya®. Para ello, hay que añadir la URL del repositorio de conectores del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable 'Customized deployment' -> 'Settings' -> `Additional jars`.

NOTE: Recuerda que, si ya tienes más de un artefacto en la lista, se deben añadir los siguientes separándolos por una coma.

=== _Stratio Virtualizer_

Para el uso de _Stratio Virtualizer_ es necesario tener configurado el conector de SAS® Viya®. Para ello, debes añadir la URL del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable 'Customized deployment' -> 'Environment' -> 'External datastores' -> `JDBC Drivers URL List` y además subir las credenciales de acceso a _Stratio KMS_.

== Transforma tus datos

=== _Stratio Rocket_

Para el uso de _Stratio Rocket_ es necesario tener configurado el conector SSCC SAS® Viya®. Para ello, debes añadir la URL del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable `Rocket extra jars` y además subir las credenciales de acceso para los _workflows_ y para _Stratio Rocket_ a _Stratio KMS_.

* 'Customized deployment' -> 'Settings' -> 'Classpath configuration' -> `Rocket extra jars`: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x.jar`.

=== _Stratio Intelligence_

Previo a la integración con el conector, es necesario configurar _Stratio Intelligence_. Se deben añadir las siguientes propiedades:

* `INTERPOLATED_ANALYTIC_ENV_CROSSDATA_CATALOG_SECRET_INSTANCE_NAME`: "${username}".
* `ANALYTIC_ENV_VAULT_PATH`: "people".
* `ANALYTIC_ENV_REQUESTS_CA_BUNDLE`: "/opt/sds/stratio_analytic/security/ca-bundle.pem".
* `ANALYTIC_ENV_HIDE_VAULT_TOKEN`: "false".

Además, en el entorno multiusuario se debe tener activada la opción "Allow artifact deployment" y tener en la ruta el valor _artifacts_.

Una vez esté configurado _Stratio Intelligence_, tienes que añadir el conector SSCC SAS® Viya® en el directorio _artifacts/spark++_++jars_ y subir las credenciales a _Stratio KMS_.

Para la subida del artefacto, este se debe descargar desde `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x` en el directorio _artifacts/spark++_++jars_ dentro del _workspace_ de _Stratio Intelligence_ realizando una petición cURL. En el caso que se está tratando, se podría realizar la siguiente petición:

[source,bash]
----
curl http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x --output sscc-sas-0.3_2.12-1.1.x
----
