= Guía de inicio rápido

== Prerrequisitos

Puedes encontrar los prerrequisitos para la instalación del conector de SSCC Elasticsearch en la xref:elasticsearch:operations-guide.adoc#_prerrequisitos[Guía de operaciones].

== Descubre tus datos

=== Agente de descubrimiento

Para instalar un agente de descubrimiento de _Stratio Data Governance_ para Elasticsearch, debes seleccionar en '_Stratio Command Center_' -> 'Deploy a Service' -> 'Connectors NoSQL' el agente `Elasticsearch Agent`.

En la instalación debes añadir la información correspondiente al proyecto de Elasticsearch a descubrir, además de la URL del repositorio de conectores donde se almacene el artefacto `sscc-elasticsearch-0.3_2.12-1.2.x`. y subir las credenciales de acceso a _Stratio KMS_.

Los campos más importantes a rellenar son:

** *_Root discovery path_*: ruta desde la cual quieres descubrir los metadatos de forma recursiva. Deben estar separados por comas, sin espacios y con una `/` al principio. Ejemplo: `/root`.
** *_Access credentials_*: nombre del secreto creado en _Stratio KMS_. Ejemplo: `<secret_name>`.
** *_Data store driver location_*: URL donde se encuentra el artefacto en el repositorio de conectores que contendrá el JAR del conector. Ejemplo: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-elasticsearch-0.3_2.12-1.2.x.jar`.

TIP: Puedes consultar más información sobre el resto de parámetros de configuración en la xref:elasticsearch:operations-guide.adoc#_agente_de_descubrimiento[Guía de operaciones].

== Virtualiza tus datos

=== Agente de Eureka

Para el uso de la BDL es necesario configurar el agente de Eureka con el conector SSCC Elasticsearch. Para ello, hay que añadir la URL del repositorio de conectores del artefacto necesario en la variable 'Customized deployment' -> 'Settings' -> `Additional jars`.

En el ejemplo que se está siguiendo, el agente de Eureka queda de esta manera:

* _Additional jars_: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-elasticsearch-0.3_2.12-1.2.x.jar`.

NOTE: Recuerda que, si ya tienes más de un artefacto en la lista, se deben añadir los siguientes separándolos por una coma.

=== _Stratio Virtualizer_

Para el uso de _Stratio Virtualizer_ es necesario tener configurado el conector SSCC Elasticsearch. Para ello, debes añadir la URL del artefacto `sscc-elasticsearch-0.3_2.12-1.2.x` en la variable 'Customized deployment' -> 'Environment' -> 'External datastores' -> `JDBC Drivers URL List` y subir las credenciales de acceso a _Stratio KMS_.

== Transforma tus datos

=== _Stratio Rocket_

Para el uso de _Stratio Rocket_ es necesario tener el conector SSCC Elasticsearch configurado. Para ello, debes añadir la URL del artefacto `sscc-elasticsearch-0.3_2.12-1.2.x` en la variable 'Customized deployment' -> 'Settings' -> 'Classpath' -> `Rocket extra jars` y, además, subir las credenciales de acceso para los _workflows_ y para _Stratio Rocket_ a _Stratio KMS_.

TIP: Puedes consultar más información sobre el resto de parámetros de configuración en la xref:elasticsearch:operations-guide.adoc#rocket-configuration[guía de operaciones].

=== _Stratio Intelligence_

Previo a la integración con el conector es necesario configurar _Stratio Intelligence_. Se deben añadir las siguientes propiedades:

* `INTERPOLATED_ANALYTIC_ENV_CROSSDATA_CATALOG_SECRET_INSTANCE_NAME`: ${username}.
* `ANALYTIC_ENV_VAULT_PATH`: "people"..
* `ANALYTIC_ENV_REQUESTS_CA_BUNDLE`: /opt/sds/stratio_analytic/security/ca-bundle.pem.
* `ANALYTIC_ENV_HIDE_VAULT_TOKEN`: "false".

Además, en el entorno multiusuario es necesario tener activada la opción "Allow artifact deployment" y tener en la ruta el valor _artifacts_.

Una vez esté configurado _Stratio Intelligence_, tienes que añadir el conector SSCC Elasticsearch en el directorio _artifacts/spark++_++jars_ y subir las credenciales de acceso a _Stratio KMS_.

Para la subida del artefacto, debes descargarlo en el directorio _artifacts/spark++_++jars_ dentro del _workspace_ de _Stratio Intelligence_ realizando una petición cURL. En el caso que se está tratando, se podría realizar la siguiente petición:

[source,bash]
----
curl http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-elasticsearch-0.3_2.12-1.2.x --output sscc-elasticsearch-0.3_2.12-1.2.x
----
