= Quick start guide

== Prerequisites

You can find the prerequisites for installing the SSCC Apache Cassandra® connector in the xref:apache-cassandra:operations-guide.adoc#_prerequisites[operations guide].

== Discover your data

=== Discovery agent

To install a _Stratio Data Governance_ discovery agent for Apache Cassandra®, select "Apache Cassandra Agent" in '_Stratio Command Center_' -> 'Deploy a Service' -> 'Connectors NoSQL'.

When installing, you need to add the information corresponding to the Apache Cassandra® project to be discovered, as well as the URL of the connectors repository where the `sscc-cassandra-0.3_2.12-1.3.x` artifact is stored and upload the access credentials to _Stratio KMS_.

The most important fields to fill in are:

* *_Root discovery path_*: path from which you want to discover metadata recursively. It must have a `/` slash at the beginning. Example: `/<keyspace_name>`.
* *_Access credentials_*: name of the secret created in xref:#create-secret[_Stratio KMS_]. Example: `cassandra-secret`.
* *_Data store driver location_*: URL where the artifact that will contain the JAR of the SSCC Apache Cassandra® connector is located in the connectors repository. Example: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x.jar`.

TIP: More information on the other configuration parameters can be found in the xref:apache-cassandra:operations-guide.adoc#_discovery_agent[operations guide].

== Virtualize your data

=== Eureka Agent

To use the BDL, you need to configure the Eureka agent with the SSCC Apache Cassandra® connector. To do this, simply add the URL of the connectors repository in the 'Customized deployment' -> 'Settings' -> `Additional jars` variable.

In the example being followed, the Eureka agent looks like this:

* _Additional jars_: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x`.

NOTE: Remember that, if you already have more than one artifact in the list, you have to add the following ones, separating them with a comma.

=== _Stratio Virtualizer_

To use _Stratio Virtualizer_, the SSCC Apache Cassandra® connector needs to be configured. To do so, you need to add the URL of the `sscc-cassandra-0.3_2.12-1.3.x` artifact in the 'Customized deployment' -> 'Environment' -> 'External datastores' -> `JDBC Drivers URL List` variable and also upload the access credentials to _Stratio KMS_.

In the example being followed, _Stratio Virtualizer_ would look like this:

* _JDBC Drivers URL List_: *http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x.jar*.

== Transform your data

=== _Stratio Rocket_

To use _Stratio Rocket_, the SSCC Apache Cassandra® connector needs to be configured. To do this, you must add the URL of the `sscc-cassandra-0.3_2.12-1.3.x` artifact in the 'Customized deployment' -> 'Settings' -> 'Classpath' -> `Rocket extra jars` variable and also upload the access credentials for the _workflows_ and for _Stratio Rocket_ to _Stratio KMS_.

In the example being followed, _Stratio Rocket_ would look like this:

* _Rocket extra jars_: *http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x.jar*.

TIP: More information on the other configuration parameters can be found in the xref:apache-cassandra:operations-guide.adoc#rocket-configuration[operations-guide].

=== _Stratio Intelligence_

Prior to integration with the connector it is necessary to configure _Stratio Intelligence_. The following properties must be added:

* `INTERPOLATED_ANALYTIC_ENV_CROSSDATA_CATALOG_SECRET_INSTANCE_NAME`: ${username}
* `ANALYTIC_ENV_VAULT_PATH`: "people".
* `ANALYTIC_ENV_REQUESTS_CA_BUNDLE`: /opt/sds/stratio_analytic/security/ca-bundle.pem
* `ANALYTIC_ENV_HIDE_VAULT_TOKEN`: "false".

In addition, in the multiuser environment it is necessary to have the "Allow artifact deployment" option enabled and to have the _artifacts_ value in the path.

Once you've configured _Stratio Intelligence_, you have to add the SSCC Apache Cassandra® connector to the _artifacts/spark++_++jars_ directory and upload the access credentials to _Stratio KMS_.

To upload the artifact, you have to download it from *http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x* to the _artifacts/spark++_++jars_ directory in the _Stratio Intelligence_ workspace by issuing a cURL request. In this case, you could make the following request:

[source,bash]
----
curl http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-cassandra-0.3_2.12-1.3.x --output sscc-cassandra-0.3_2.12-1.3.x
----
