= Matriz de compatibilidad

Los módulos compatibles con el conector SSCC SAP HANA, junto con las distintas opciones que se soportan a partir de la versión que se indica del artefacto, son los siguientes:

[cols="1,1,1"]
|===
|Módulo |Capacidad |Conector

| _Stratio Data Governance_
| Descubrimiento
| >= sscc-saphana-0.3_2.12-1.1.x

| _Stratio BDL_
| Virtualización
| >= sscc-saphana-0.3_2.12-1.1.x

| _Stratio Virtualizer_
| Lectura/Escritura/Acceso nativo
| >= sscc-saphana-0.3_2.12-1.1.x

| _Stratio Rocket_
| Lectura/Escritura virtualizada
| >= sscc-saphana-0.3_2.12-1.1.x

| _Stratio Intelligence_
| Lectura/Escritura virtualizada
| >= sscc-saphana-0.3_2.12-1.1.x
|===

== Compatibilidad con versiones de SAP HANA

Se ha validado la compatibilidad del conector para la versión hanaexpress:2.00.045.00.20200121.1.

== Versiones del conector SSCC SAP HANA en la plataforma

El conector necesita estar acompañado de un artefacto con el _driver JDBC_ de SAP HANA. Al estar desacoplado, se puede utilizar el mismo conector con diferentes versiones.

La versión actual del conector está validada contra las siguientes versiones del _driver JDBC_:

|===
| Versión del _driver JDBC_ | Artefacto del repositorio de conectores

| 2.15.10
| _ngdbc-2.15.10.jar_
|===

En https://search.maven.org/artifact/com.sap.cloud.db.jdbc/ngdbc[este enlace] se pueden descargar los distintos _drivers_ disponibles.
