= Guía de inicio rápido

El propósito de esta guía es explicar brevemente cómo integrar el modelo de datos de la plataforma SAS® Grid Manager en la plataforma _Stratio Generative AI Data Fabric_.

== Prerrequisitos

Puedes encontrar los prerrequisitos para la instalación del conector de SSCC SAS® Grid Manager en la xref:sas-grid-manager:operations-guide.adoc#_prerrequisitos[guía de operaciones].

NOTE: Ten en cuenta que en esta guía de inicio rápido se utilizará el *modo de autenticación MD5*.

== Descubre tus datos

=== Agente de descubrimiento

Para instalar un agente de descubrimiento de _Stratio Data Governance_ para SAS® Grid Manager debes seguir la ruta '_Stratio Command Center_' -> 'Deploy a Service' -> 'Connectors FS' y seleccionar el agente "SAS® Grid Manager Agent".

En la instalación debes añadir las URL del repositorio de conectores donde se almacenan los artefactos necesarios y subir las credenciales de acceso a _Stratio KMS_.

Los campos más importantes a rellenar son:

* *_Root discovery path_*: ruta desde la cual quieres descubrir los metadatos de forma recursiva.
* *_Custom Service URL_*: URL JDBC usada para conectarse al sistema de ficheros de SAS® Grid Manager. Ejemplo: `sasgrid.stratio.com[:22]`.
* *_Access credentials_*: nombre del secreto creado en _Stratio KMS_. Ejemplo: `sasgrid-secret`.
* *_SSCC driver location_*: URL donde se encuentra el artefacto en el repositorio de conectores que contendrá el JAR del conector SSCC SAS® Grid Manager. Ejemplo: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x.jar`.
* *_GLOB filter_*. Ejemplo: `stratioarchitecture/test++_++data/`.

TIP: Puedes consultar más información sobre el resto de parámetros de configuración en la xref:sas-grid-manager:operations-guide.adoc[guía de operaciones].

Una vez terminado el proceso de descubrimiento, el almacén de datos aparecerá en la interfaz de usuario de _Stratio Data Governance_.

== Virtualiza tus datos

=== Agente de Eureka

Para el uso de la BDL es necesario configurar el agente de Eureka con el conector SSCC SAS® Grid Manager. Para ello, hay que añadir la URL del repositorio de conectores del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable 'Customized deployment' -> 'Settings' -> `Additional jars`.

NOTE: Recuerda que, si ya tienes más de un artefacto en la lista, se deben añadir los siguientes separándolos por una coma.

=== _Stratio Virtualizer_

Para el uso de _Stratio Virtualizer_ es necesario tener configurado el conector de SSCC SAS® Grid Manager. Para ello, debes añadir la URL del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable 'Customized deployment' -> 'Environment' -> 'External datastores' -> `JDBC Drivers URL List` y además subir las credenciales de acceso a _Stratio KMS_.

== Transforma tus datos

=== _Stratio Rocket_

Para el uso de _Stratio Rocket_ es necesario tener el conector de SAS® Grid Manager configurado. Para ello, debes añadir la URL del artefacto `sscc-sas-0.3_2.12-1.1.x` en la variable `Rocket extra jars` y además subir las credenciales de acceso para los _workflows_ y para _Stratio Rocket_ a _Stratio KMS_.

* 'Customized deployment' -> 'Settings' -> 'Classpath configuration' -> `Rocket extra jars`: `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-sas-0.3_2.12-1.1.x.jar`.

=== _Stratio Intelligence_

Previo a la integración con el conector es necesario configurar _Stratio Intelligence_, tal y como aparece descrito en xref:ROOT:quick-start-guide#_stratio_intelligence[la guía de inicio rápido general].

Para acceder y explotar los datos de SAS® Grid Manager se debe configurar de la siguiente manera:

* Añade el conector SSCC SAS® Grid Manager a la instancia de _Stratio Intelligence_:
** Navega hasta '_Stratio Command Center_' -> 'Services' -> '<Tu Namespace>' -> 'intelligence' -> 'Edit' -> 'Customize deployment' -> 'Settings' -> 'Analytic Environment Settings' -> 'Extra jars to Spark Context Configuration'.
** Añade al campo _Spark classpath extra jars_ la URL del conector `http://connectors.<tenant>-<namespace>/v1/api/artifact/sscc-s3-0.3_2.12-1.0.x.jar`.
** Añade esa misma URL al _classpath_ de Apache Spark™.
+
IMPORTANT: Debido a que _Stratio Intelligence_ necesita disponer del conector en tiempo de inicialización de Apache Spark™, es necesario que el conector se encuentre en el _classpath_ al arrancar el _Notebook_. Actualmente, la manera de hacerlo es editando el descriptor correspondiente a _Stratio Intelligence_ en Kubernetes y añadir la URL del conector a la variable de entorno `ANALYTIC_ENV_SPARK_HOME_EXTRA_JARS`.

* xref:sas-grid-manager:operations-guide.adoc#_prerrequisitos[Sube las credenciales de acceso a __Stratio KMS__].

Tras aplicar estos cambios, deberías poder acceder a la colección virtualizada de SAS® Grid Manager mediante SparkSQL a través del catálogo. Consulta más información y los modos de acceso disponibles en la xref:sas-grid-manager:operations-guide.adoc#_stratio_intelligence[guía de operaciones].
