= Matriz de compatibilidad

Los módulos compatibles con PostgreSQL®, junto con las distintas opciones que se soportan a partir de la versión que se indica del artefacto, son los siguientes:

[cols="1,1,1"]
|===
|Módulo |Capacidad |Conector

| _Stratio Data Governance_
| Descubrimiento
| >= sscc-postgresql-0.3_2.12-1.1.x

| _Stratio BDL_
| Virtualización
| >= sscc-postgresql-0.3_2.12-1.1.x

| _Stratio BDL_
| Mapeo semántico operacional
| >= sscc-postgresql-0.3_2.12-1.1.x

| _Stratio Virtualizer_
| Lectura/Escritura/Acceso nativo
| >= sscc-postgresql-0.3_2.12-1.1.x

| _Stratio Rocket_
| Lectura/Escritura/Escritura virtualizada/Acceso nativo
| >= sscc-postgresql-0.3_2.12-1.1.x

| _Stratio Intelligence_
| Lectura/Escritura/Escritura virtualizada/Acceso nativo
| >= sscc-postgresql-0.3_2.12-1.1.x
|===

== Compatibilidad con versiones de PostgreSQL®

Se ha validado la compatibilidad del conector para las versiones de PostgreSQL® mayores o iguales a la 8.2.

== Versiones del _driver JDBC_ soportadas

El connector SSCC PostgreSQL® ya dispone del _driver_ de PostgreSQL® incluido.

La versión actual del conector está validada contra las siguientes versiones del _driver JDBC_:

|===
| Versión del _driver JDBC_ | Versión del conector SSCC PostgreSQL®
| 42.6.0 | sscc-postgresql-0.3_2.12-1.1.x
|===

En https://central.sonatype.com/artifact/org.postgresql/postgresql[este enlace] se pueden ver los distintos _drivers_ disponibles.

La versión actual del controlador debe ser compatible con PostgreSQL® 8.2 y superior utilizando la versión 3.0 del protocolo PostgreSQL®. Consulta su https://jdbc.postgresql.org/documentation/[documentación].

== Descubrimiento con optimización automática

El conector SSCC PostgreSQL® incluye, desde la versión 0.3_2.12-1.4.x, mecanismos de optimización automática durante el proceso de descubrimiento.
