= Matriz de compatibilidad

Los módulos compatibles con el conector SSCC IBM Db2, junto con las distintas opciones que se soportan a partir de la versión que se indica del artefacto, son los siguientes:

[cols="1,1,1"]
|===
|Módulo |Capacidad |Conector

| _Stratio Data Governance_
| Descubrimiento
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio BDL_
| Virtualización
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Virtualizer_
| Lectura/Escritura/Acceso nativo
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Rocket_
| Lectura/Escritura virtualizada/Acceso nativo
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Intelligence_
| Lectura/Escritura virtualizada/Acceso nativo
| >= sscc-db2-0.3_2.12-1.4.x
|===

== Compatibilidad con versiones de IBM Db2

Se ha validado la compatibilidad del conector para IBM Db2 11.5.0.

== Versiones del _driver JDBC_ soportadas

El conector necesita estar acompañado de un artefacto con el _driver JDBC_ de IBM Db2. Al estar desacoplado, se puede utilizar el mismo conector con diferentes versiones.

La versión actual del conector está validada contra las siguientes versiones del _driver JDBC_:

|===
| Versión del _driver JDBC_ | Artefacto del repositorio de conectores

| 11.5.0
| _jcc-11.5.0.0.jar_
|===

En https://search.maven.org/artifact/com.ibm.db2/jcc/11.5.0.0/jar[este enlace] se pueden descargar los distintos _drivers_ disponibles.

TIP: Aquí puedes consultar https://www.ibm.com/docs/en/db2-for-zos/11?topic=sqlj-jdbc-driver-database-version-compatibility[la matriz de compatibilidad entre las versiones del _driver JDBC_ y IBM Db2].
