= Changelog Spark

== 3.1.1-1.3.0 (February 14, 2022)

* [SPK-1339] Fix vulnerabilities: Conda 37_4.10.3 and Google Cloud hadoop3-2.2.3
* [SPK-1348] Support Stratio external-hdfs-plugin connector
* [SPK-1344] Set en_US.UTF8 as default locale to avoid problems related with Charsets
* [SPK-1320] Update check hdfs role framework for data locality in Mesos
* [SPK-1333] Implement Custom Dynamic classloaders in Spark Session and manage them
* [SPK-1351] New version for external-hdfs-plugin to avoid delegation tokens problem with RDDs
* [SPK-1361] Fix calico network validation in Spark Dispatcher
* [SPK-1365] Avoid tests in installation of python building Dockerfile
* [CON-797] Add Hive Dialect
* [SPK-1378] Limit use of SELECT reflect & SELECT java_method
* [SPK-1346] Auto manage owners to delete executors and configmaps when delete driver pod
* [SPK-1384] Make protected validateName to new Crossdata functionality
* [SPK-1377] Fix dependencies (anchore) for external-hdfs-plugin
* [SPK-1389] Fix SPARK-34377,SPARK-34385 parquet dates in old versions (generated by 2.4.4)
* [SPK-1406] Mount configmap for hadoop and krb5 in executors

== 3.1.1-1.2.0 (September 29, 2021)

* [SPK-1312] Fix SSO bypass in History Server and Spark Dispatcher
* [SPK-1313] Added health check for History Server (spark.history.fs.max_time_between_updates)
* [SPK-1274] Add HTTPS_ONLY env variable to prevent jars launched from untrusted repositories
* [SPK-1317] Enable SparkR profile

== 3.1.1-1.1.0 (August 25, 2021)

* [SPK-1256] Added native libraries for Hadoop 3.2.0 (supporting Lz4 and Zstd)
* [SPK-1260] Update delta-lake version to 1.0.0 and urllib3 to 1.26.6
* [SPK-1290] Fix metrics file in executors when log level is enabled in Kubernetes
* [SPK-1281] Enhance Vault CAs download (cache and one request download for all CAs)
* Upgraded commons-compress to 1.21

== 3.1.1-1.0.0 (June 05, 2021)

* [SPK-1174] Docker and poms updated
* [SPK-1181] Added Vault Integration and secret management from 3.0.1-1.1.0
* [SPK-1184] Add SSO to Spark dispatcher and History Server
* [FLOW-1840] Reenable Hive tests failing due locale in Jenkins
* [SPK-1188] Add soft failure if we don't have permissions to read volumes allowed in Vault
* [SPK-1185] Add SUPPRESS in Mesos integration
* [SPK-1182] Support Calico in mesos, and limit jobs into the same tenant network launched by the Spark Dispatcher
* [SPK-1192] Fix memory overhead for drivers in Mesos (spark.mesos.driver.memoryOverhead)
* [SPK-1195] Streaming tab in History Server and add Fix SPARK-34731 preventing ConcurrentException in AsyncEventQueue
* [SPK-1190] Shuffle cleaning
* [SPK-1193] Added Spark Property spark.driver.noresources.timeout (default to 1 hour) where driver should die after that amount of time if Mesos doesn't give it resources
* [SPK-1215] Added async/sync offset commit with retry policy in kafka input
* [SPK-1203] Azure Data Lake gen 1 and 2 / S3/ GCS / Blob integration with vault. Included delta lake 0.7.0 dependency
* [SPK-1197] Security fixes to avoid critical vulnerabilities and Preventing log forging
* [SPK-1218] Change maven version to DEPLOYONPRs
* [SPK-1202] Enhance optimizer performance where there are a lot of environmental variables
* [SPK-1207] Mesos tryAndLock in all operations to avoid framework errors and shuffle retry attempts
* [SPK-1204] Monitoring with Prometheus
* [SPK-1206] Mesos blacklist agent improvement
* [SPK-1205] External shuffle security
* [SPK-1210] Secret broadcast variables
* [SPK-1216] Custom python environment for pySpark in 3.1.1
* [SPK-1217] Support different keytabs for different users in local mode
* [SPK-1208] Data locality in HDFS
* [SPK-1209] Fix log forgery in Spark dispatcher
* [SPK-1228] K8S basic integration
* [SPK-1213] Filter Spark UI by Cookie
* [SPK-1223] Redact sensitive properties in Spark UI - API
* [SPK-1229] Stratio log format and levels (executors and drivers) in K8s
* [SPK-1226] Stratio Labels in K8S
* [SPK-1232] Prometheus metrics support in K8S
* [SPK-1196] Write metrics in log when job is finishing and metrics are enabled
* [SPK-1236] External shuffle registration sync (if registration is not possible, it will kill the driver)
* [SPK-1242] Set conda autoupdate to false
* [SPK-1219] Support NetApp integration
* [SPK-1198] Retry n times (waiting m seconds between attempts) in Vault operations
* [CON-489] Add AS400 JDBC dialect (based on DB2 dialect)
* [CON-210] Add SAP HANA JDBC Dialect
