= Compatibility matrix

NOTE: IBM Db2 for iSeries AS400 software is commercially licensed, so registration and acceptance of its license terms are required.

The modules that are compatible with the SSCC AS400 connector along with the different options that are supported starting with the version of the artifact specified are as follows:

[cols="1,1,1"]
|===
|Module |Capacity |Connector

| _Stratio Data Governance_
| Discovery
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio BDL_
| Virtualization
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Virtualizer_
| Read/Write/Native access
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Rocket_
| Read/Virtualized write/Native access
| >= sscc-db2-0.3_2.12-1.4.x

| _Stratio Intelligence_
| Read/Virtualized write/Native access
| >= sscc-db2-0.3_2.12-1.4.x
|===

== Compatibility with IBM Db2 iSeries AS400 versions

Connector compatibility has been validated for version 7.5 of the data store.

== Supported JDBC driver versions

The connector needs to be coupled with an artifact with the IBM Db2 iSeries AS400 JDBC driver. Since it's decoupled, you can use the same connector with different versions.

The current version of the connector supports the following JDBC driver versions:

|===
| JDBC driver version | Artifact from the connectors repository

| 11.1
| _jt400-11.1.jar_
|===

The different drivers can be downloaded from https://search.maven.org/artifact/net.sf.jt400/jt400[this link].
